shopping_site/more_polls/urls.py
from django.urls import path

from . import views

app_name = 'more_polls'
# generic views
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]
#basic way. calls a function from given file, in this case, "view.py"
#urlpatterns = [
#   path('', views.index, name='index'),
#	path('<int:question_id>/', views.detail, name='detail'),
#	path('<int:question_id>/results/', views.results, name='results'),
#	path('<int:question_id>/vote/', views.vote, name='vote'),
#]

shopping_site/polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

shopping_site/shopping_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('polls/', include('polls.urls')),
	path('more_polls/', include('more_polls.urls')),
    path('admin/', admin.site.urls),
]

shopping_site/more_polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date_published')

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

	# define admin page display properties
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'From last 24h?'


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

shopping_site/polls/models.py
from django.db import models

# Create your models here.

shopping_site/more_polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
#from django.template import loader
from .models import Question

### CLASSIC MODE
### NOT USED

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'more_polls/index.html', context)
	#another way would be >>
	#template = loader.get_template('polls/index.html')
    #return HttpResponse(template.render(context, request))


def detail(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	#another way would be >>
	#try:
	#    question = Question.objects.get(pk=question_id)
	#except Question.DoesNotExist:
	#    raise Http404("Question does not exist")
	return render(request, 'more_polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'more_polls/results.html', {'question': question})


def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		# Redisplay the question voting form.
		return render(request, 'more_polls/detail.html', {
			'question': question,
			'error_message': "You didn't select a choice.",
		})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		# Always return an HttpResponseRedirect after successfully dealing
		# with POST data. This prevents data from being posted twice if a
		# user hits the Back button.
		return HttpResponseRedirect(reverse('more_polls:results', args=(question.id,)))

### GENERIC VIEW MODE
### IN USE

class IndexView(generic.ListView):
	template_name = 'more_polls/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		"""
		Return the last five published questions (not including those set to be
		published in the future).
		"""
		return Question.objects.filter(pub_date__lte=timezone.now()
				).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
	model = Question
	template_name = 'more_polls/detail.html'


class ResultsView(generic.DetailView):
	model = Question
	template_name = 'more_polls/results.html'

shopping_site/polls/views.py
from django.shortcuts import render

# Create your views here.

shopping_site/more_polls/templates/more_polls/detail.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Question Detail: {{ question.question_text }}</title>
</head>
<body>
	<h1>{{ question.question_text }}</h1>

	{% if error_message %}
		<p><strong>{{ error_message }}</strong></p>
	{% endif %}

	<form action="{% url 'more_polls:vote' question.id %}" method="post">
		{% csrf_token %}
		{% for choice in question.choice_set.all %}
			<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
			<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
		{% endfor %}
		<input type="submit" value="Vote">
	</form>
</body>
</html>

shopping_site/more_polls/templates/more_polls/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'more_polls/css/style.css' %}">
	<meta charset="utf-8">
	<title>Latest Questions List</title>
</head>
<body>
	{% if latest_question_list %}
		<ul>
		{% for question in latest_question_list %}
			{# hardcored mode #}
			{#<li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>#}
			<li><a href="{% url 'more_polls:detail' question.id %}">{{ question.question_text }}</a></li>
		{% endfor %}
		</ul>
	{% else %}
		<p>No polls are available.</p>
	{% endif %}
</body>
</html>

shopping_site/more_polls/templates/more_polls/results.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Question Detail: {{ question.question_text }}</title>
</head>
<body>
	<h1>{{ question.question_text }}</h1>

	<ul>
	{% for choice in question.choice_set.all %}
		<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
	{% endfor %}
	</ul>

	<a href="{% url 'more_polls:detail' question.id %}">Vote again?</a>
</body>
</html>